import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
    container: { flex: 1, justifyContent: 'flex-start', alignItems: 'center', backgroundColor: '#e8e8e8', paddingTop: 5 },
    title: { fontSize: 28, fontWeight: 'bold', color: '#275636', marginBottom: 16, marginTop: 15 },
    searchRow: {
        flexDirection: 'row',
        alignItems: 'center',
        width: '90%',
        marginBottom: 16,
    },
    searchInput: {
        flex: 1,
        height: 40,
        borderColor: '#ccc',
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 12,
        backgroundColor: '#fff',
    },
    addButton: {
        marginLeft: 8,
        backgroundColor: '#275636',
        borderRadius: 8,
        width: 40,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addButtonText: {
        color: '#fff',
        fontSize: 28,
        fontWeight: 'bold',
        marginTop: -2,
    },
    userItem: {
        width: '95%',
        backgroundColor: '#fff',
        paddingVertical: 14,
        paddingHorizontal: 18,
        borderRadius: 12,
        marginBottom: 14,
        elevation: 1,
        flexDirection: 'column',
        width: 325
    },
    userName: {
        fontSize: 18,
        fontWeight: 'bold',
        marginBottom: 2
    },
    userEmail: {
        fontSize: 16,
        color: '#555',
    },
    subtitle: { fontSize: 18, color: '#222' },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.3)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: 320,
        backgroundColor: '#fff',
        borderRadius: 14,
        padding: 20,
        elevation: 5,
    },
    modalTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#222',
        marginBottom: 16,
        textAlign: 'center',
    },
    modalInput: {
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        marginBottom: 10,
        fontSize: 16,
        backgroundColor: '#f7f7fa',
    },
    modalCancelBtn: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        backgroundColor: '#f3f3f3',
        marginRight: 8,
    },
    modalSaveBtn: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        borderRadius: 8,
        backgroundColor: '#275636',
    },
    modalPicker: {
        backgroundColor: '#f7f7fa',
        borderWidth: 1,
        borderColor: '#ccc',
        borderRadius: 8,
        marginBottom: 10,
        height: 48,
        justifyContent: 'center',
    },
    actionModalContent: {
        width: 280,
        backgroundColor: '#fff',
        borderRadius: 14,
        padding: 20,
        elevation: 5,
        alignItems: 'center',
    },
    actionBtn: {
        width: '100%',
        backgroundColor: '#275636',
        borderRadius: 8,
        paddingVertical: 12,
        alignItems: 'center',
        marginBottom: 12,
    },
    actionBtnText: {
        color: 'white',
        fontWeight: 'bold',
        fontSize: 16,
    },
    backBtn: {
        position: 'absolute',
        top: 19,
        left: 16,
        zIndex: 10,
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 4,
        elevation: 2,
    },
});

export default styles; 