import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#e8e8e8' },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 20,
        backgroundColor: '#275636',
    },
    backIcon: {
        position: 'absolute',
        left: 12,
        top: 15,
        zIndex: 2,
        padding: 4,
    },
    headerTitle: { color: '#fff', fontSize: 20, fontWeight: 'bold', letterSpacing: 1, },
    searchBarRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginHorizontal: 8,
        marginTop: 8,
        marginBottom: 8,
    },
    searchBarContainer: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f3f3f3',
        borderRadius: 16,
        paddingHorizontal: 8,
        height: 44,
        marginRight: 8,
    },
    searchInput: {
        flex: 1,
        fontSize: 16,
        marginLeft: 8,
        color: '#222',
    },
    sectionTitle: { fontWeight: 'bold', fontSize: 16, marginLeft: 16, marginTop: 8, marginBottom: 4, color: '#222' },
    popularSearches: { flexDirection: 'row', marginLeft: 8, marginBottom: 8 },
    popularSearchItem: { backgroundColor: '#f3f3f3', borderRadius: 18, paddingHorizontal: 16, paddingVertical: 8, marginHorizontal: 4 },
    popularSearchText: { color: '#444', fontWeight: '500' },
    productCard: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 12,
        marginHorizontal: 12,
        marginVertical: 6,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
    },
    productImage: { width: 60, height: 80, resizeMode: 'contain', marginRight: 12 },
    productName: { fontWeight: 'bold', fontSize: 15, marginBottom: 2, color: '#222' },
    productDesc: { color: '#666', fontSize: 13, marginBottom: 2, width: width * 0.38 },
    productPrice: { color: '#275636', fontWeight: 'bold', fontSize: 15 },
    iconRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
    },
    adminIcon: {
        backgroundColor: '#e0f2e9',
        borderRadius: 8,
        padding: 6,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 'auto',
    },
    addButton: {
        backgroundColor: '#275636',
        borderRadius: 16,
        width: 32,
        height: 32,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: 'auto',
    },
    addButtonText: {
        color: '#fff',
        fontSize: 22,
        fontWeight: 'bold',
    },
    addProductButton: {
        backgroundColor: '#275636',
        borderRadius: 8,
        width: 44,
        height: 44,
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalInput: {
        height: 40,
        paddingHorizontal: 12,
        backgroundColor: '#f7f7fa',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ddd',
        marginBottom: 12,
        fontSize: 16,
        color: '#222',
    },
    actionModalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    actionModalContent: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 24,
        width: 300,
        alignItems: 'center',
    },
    actionModalTitle: {
        fontSize: 15,
        fontWeight: 'bold',
        color: '#222',
        marginBottom: 18,
        textAlign: 'center',
    },
    actionUpdateBtn: {
        backgroundColor: '#275636',
        borderRadius: 10,
        paddingVertical: 16,
        alignItems: 'center',
        width: 260,
        marginBottom: 14,
    },
    actionUpdateBtnText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
        textAlign: 'center',
    },
    actionDeleteBtn: {
        backgroundColor: '#e53935',
        borderRadius: 10,
        paddingVertical: 16,
        alignItems: 'center',
        width: 260,
        marginBottom: 14,
    },
    actionDeleteBtnText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 18,
        textAlign: 'center',
    },
    actionCancelBtn: {
        backgroundColor: '#f3f3f3',
        borderRadius: 10,
        paddingVertical: 12,
        alignItems: 'center',
        width: 90,
        marginTop: 4,
    },
    actionCancelBtnText: {
        color: '#888',
        backgroundColor: '#f3f3f3',
        fontSize: 16,
        textAlign: 'center',
    },
});

export default styles; 